message("Running FindPhysx")

SET (PHYSX_SEARCH_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../deps/physx)
SET (PHYSX_DEFAULT_LIBDIR ${PHYSX_SEARCH_PATH}/lib)
SET	(PHYSX_DEFAULT_INCLUDE ${PHYSX_SEARCH_PATH}/include)
SET (PHYSX_LIBDIR_DEBUG ${PHYSX_DEFAULT_LIBDIR}/debug)
SET (PHYSX_LIBDIR_RELEASE ${PHYSX_DEFAULT_LIBDIR}/release)

# Find include path

FIND_PATH(
	PHYSX_INCLUDE_DIR
	PxPhysicsAPI.h
	PATHS ${PHYSX_DEFAULT_INCLUDE}
)




# Finds Release Libraries

FIND_LIBRARY (
	PHYSX_LIBRARY
	NAMES PhysX3_x86 PhysX3_x64 PhysX3
	PATHS ${PHYSX_LIBDIR_RELEASE}
)
FIND_LIBRARY (
	PHYSX_COMMON_LIBRARY
	NAMES PhysX3Common_x86 PhysX3Common_x64 PhysX3Common
	PATHS ${PHYSX_LIBDIR_RELEASE}
	)
	
FIND_LIBRARY (
	PHYSX_COOKING_LIBRARY
	NAMES PhysX3Cooking_x86 PhysX3Cooking_x64 PhysX3Cooking
	PATHS ${PHYSX_LIBDIR_RELEASE}
	)
	
FIND_LIBRARY (
	PHYSX_EX_LIBRARY
	PHYSX_EX_LIBRARY
	NAMES PhysX3Extensions_x86 PhysX3Extensions_x64 PhysX3Extensions
	PATHS ${PHYSX_LIBDIR_RELEASE}
	)
	
FIND_LIBRARY (
	PHYSX_CK_LIBRARY
	NAMES PhysX3CharacterKinematic_x86 PhysX3CharacterKinematic_x64 PhysX3CharacterKinematic
	PATHS ${PHYSX_LIBDIR_RELEASE}
	)

FIND_LIBRARY (
	PHYSX_FXML_LIBRARY
	NAMES PsFastXml_x86 PsFastXml_x64 PsFastXml
	PATHS ${PHYSX_LIBDIR_RELEASE}
	)

FIND_LIBRARY (
	PHYSX_FOUNDATION_LIBRARY
	NAMES PxFoundation_x86 PxFoundation_x64 PxFoundation
	PATHS ${PHYSX_LIBDIR_RELEASE}
	)

FIND_LIBRARY (
	PHYSX_PVD_LIBRARY
	NAMES PxPvdSDK_x86 PxPvdSDK_x64 PxPvdSDK
	PATHS ${PHYSX_LIBDIR_RELEASE}
	)

FIND_LIBRARY (
	PHYSX_TASK_LIBRARY
	NAMES PxTask_x86 PxTask_x64 PxTask
	PATHS ${PHYSX_LIBDIR_RELEASE}
	)


# Finds debug libraries

FIND_LIBRARY (
	PHYSX_LIBRARY_DEBUG
	NAMES PhysX3DEBUG_x86 PhysX3DEBUG_x64 PhysX3DEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)
	
FIND_LIBRARY (
	PHYSX_COMMON_LIBRARY_DEBUG
	NAMES PhysX3CommonDEBUG_x86 PhysX3CommonDEBUG_x64 PhysX3CommonDEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)
	
FIND_LIBRARY (
	PHYSX_COOKING_LIBRARY_DEBUG
	NAMES PhysX3CookingDEBUG_x86 PhysX3CookingDEBUG_x64 PhysX3CookingDEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)

FIND_LIBRARY (
	PHYSX_EX_LIBRARY_DEBUG
	NAMES PhysX3ExtensionsDEBUG_x86 PhysX3ExtensionsDEBUG_x64 PhysX3ExtensionsDEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)

FIND_LIBRARY (
	PHYSX_CK_LIBRARY_DEBUG
	NAMES PhysX3CharacterKinematicDEBUG_x86 PhysX3CharacterKinematicDEBUG_x64 PhysX3CharacterKinematicDEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)

FIND_LIBRARY (
	PHYSX_FXML_LIBRARY_DEBUG
	NAMES PsFastXmlDEBUG_x86 PsFastXmlDEBUG_x64 PsFastXmlDEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)

FIND_LIBRARY (
	PHYSX_FOUNDATION_LIBRARY_DEBUG
	NAMES PxFoundationDEBUG_x86 PxFoundationDEBUG_x64 PxFoundationDEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)

FIND_LIBRARY (
	PHYSX_PVD_LIBRARY_DEBUG
	NAMES PxPvdSDKDEBUG_x86 PxPvdSDKDEBUG_x64 PxPvdSDKDEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)

FIND_LIBRARY (
	PHYSX_TASK_LIBRARY_DEBUG
	NAMES PxTaskDEBUG_x86 PxTaskDEBUG_x64 PxTaskDEBUG
	PATHS ${PHYSX_LIBDIR_DEBUG}
	)


IF( PHYSX_INCLUDE_DIR AND 

	PHYSX_LIBRARY AND 
	PHYSX_COMMON_LIBRARY AND 
	PHYSX_COOKING_LIBRARY AND 
	PHYSX_EX_LIBRARY AND 
	PHYSX_CK_LIBRARY AND
	PHYSX_FXML_LIBRARY AND
	PHYSX_FOUNDATION_LIBRARY AND
	PHYSX_PVD_LIBRARY AND
	PHYSX_TASK_LIBRARY AND


	PHYSX_LIBRARY_DEBUG AND 
	PHYSX_COMMON_LIBRARY_DEBUG AND 
	PHYSX_COOKING_LIBRARY_DEBUG AND 
	PHYSX_EX_LIBRARY_DEBUG AND 
	PHYSX_CK_LIBRARY_DEBUG AND
	PHYSX_FXML_LIBRARY_DEBUG AND
	PHYSX_FOUNDATION_LIBRARY_DEBUG AND
	PHYSX_PVD_LIBRARY_DEBUG AND
	PHYSX_TASK_LIBRARY_DEBUG
	)
	SET(PHYSX_FOUND "YES")
	message("PHYSX Added")
ELSE()
	SET(PHYSX_FOUND "NO")
	message("PHYSX Not Found")
ENDIF()
